apiVersion: v1
kind: Service
metadata:
  name: kubedog
  labels:
    app: kubedog
  namespace: kubedog-namespace
spec:
  type: NodePort
  ports:
  - name: kubedog
    port: 5000
    targetPort: 80
    nodePort: 32766
  selector:
    app: kubedog