apiVersion: v1
kind: Service
metadata:
  name: kubedog
  labels:
    app: kubedog
  namespace: kubedog-namespace
spec:
  type: LoadBalancer
  ports:
  - name: kubedog
    port: 80
    targetPort: 80
  selector:
    app: kubedog